### ISSUE TITLE
command 'rainingin.toggleDownpour' not found

### ISSUE THREAD

**Issue by AliMilani13** [torshepherd/raining-in-vscode#7]
when I'm trying to use the extension, it gives me the error, in the title. 

I tried to re install the extension and even re install VSCode but still shows me this error. 

I use VSCode 1.94.2 on Windows 11 22H2

**Comment by torshepherd** [comment]
Hmm I should probably deprecate this extension as it's unfortunately pretty hard to maintain. It depends on using a hack to modify the background html of the vscode window itself and add an svg animation. As such, any update where the vscode changes the html structure breaks this extension.

If you really wanted to use this extension though, im happy to fix it :) . But it may break again

**Comment by 0xN1nja** [comment]
hey @torshepherd 

I don't know if you remember me, but I’ve been using this extension for the past two years and even contributed to it two years ago (it was my first PR :P). This has been my favorite vscode extension. Whenever it used to rain, I used it and played "raining in miami" in the background. It's sad to see that you're no longer maintaining it (I know that it modifies some custom css, it breaks with every vscode update, and is really hard to maintain) :(

**Comment by torshepherd** [comment]
That is nice to hear. I'll happily fix it 😄

**Comment by AliMilani13** [comment]
> Hmm I should probably deprecate this extension as it's unfortunately pretty hard to maintain. It depends on using a hack to modify the background html of the vscode window itself and add an svg animation. As such, any update where the vscode changes the html structure breaks this extension.
> 
> If you really wanted to use this extension though, im happy to fix it :) . But it may break again


the problem is not the extension itself and how it works I guess. every time VSCode gets a new update, it breaks some extensions. 

in the latest version of VSCode ( 1.94.2 ), it break the extension. I remember back in the day, VSCode 1.72 also broke the Emmet extension. 

it is so unfortunate to see this. 

I filed an issue to them but they marked it as "caused by extension" but in reality, it actually caused by the editor. 



I like your extension. when you combine it with themes like Synthwave, it gives fascinating feeling. I would like to continue using it. I appreciate if you fix it. of course at your free time. 👍

**Comment by torshepherd** [comment]
Just pushed a fix with version 1.1.0. Can you guys let me know if this fixes it for you? If so I'll close this next week

**Comment by AliMilani13** [comment]
> Just pushed a fix with version 1.1.0. Can you guys let me know if this fixes it for you? If so I'll close this next week

Hi. thank you for efforts you put on it. unfortunately it works for a second. for example if you toggle downpour it will work for just a second and stops.

**Comment by torshepherd** [comment]
Should be fixed with 1.1.1, thanks for letting me know

**Comment by AliMilani13** [comment]
> Should be fixed with 1.1.1, thanks for letting me know

thanks for your time and effort on this. 

It is now working. problem solved.
